# Use a lightweight Python base image
FROM python:3.11.1-slim

# Set the working directory inside the container
WORKDIR /app

# Copy dependency and source files to container
COPY requirements.txt .
COPY main.py .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the main script when the container starts
CMD ["python", "main.py"]